DEFAULT_RETRACTION_HEIGHT = 50
DEFAULT_WASH_WAIT = 5

DEFAULT_LAYER_HEIGHT = 50
DEFAULT_PROJECTOR_X = 1280
DEFAULT_PROJECTOR_Y = 800
DEFAULT_UM_PER_PX = 50
DEFAULT_UM_PER_STEP = 500

DEFAULT_TRAY_1_LOC = -0.1
DEFAULT_TRAY_2_LOC = 5.0
DEFAULT_TRAY_3_LOC = 10.0
DEFAULT_WASH_TRAY_LOC = 15.0

DEFAULT_WASH_POSITION = 12
